// @ts-ignore The mockSESsendEmail function is a mock generated by jest: it does not exist in the original module
import { mockSESsendTemplatedEmail } from "aws-sdk";
import { sendSecretCodeEmail } from "./send-email";

jest.mock("aws-sdk");
jest.mock("aws-lambda");

describe("create-auth-challenge.sendSecretCodeEmail", () => {
  test("send the secret code email", async () => {
    await sendSecretCodeEmail("foo@gogaile.test", "bar@do.com", {
      secretLoginCode: "123456",
    });

    expect(mockSESsendTemplatedEmail).toHaveBeenCalledTimes(1);
    expect(mockSESsendTemplatedEmail).toHaveBeenLastCalledWith({
      Source: "foo@gogaile.test",
      Destination: { ToAddresses: ["bar@do.com"] },
      Template: "idp-secret-code-en",
      TemplateData: '{"secretLoginCode":"123456"}',
    });
  });
});
